name: Build and Deploy Web

on:
  push:
    branches:
      - react-native-web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install node_modules
        working-directory: packages/web
        run: yarn install --frozen-lockfile

      - name: Deploy ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/web/build
          publish_branch: docs
